kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-persistent-volume-claims
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi